apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: vijay2359/cus-wordpress:${IMAGE_TAG}  # Image tag from Jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: wordpress-config  # Load from ConfigMap
        env:
        - name: WORDPRESS_DB_PASSWORD
          value: "${DB_PASSWORD}"  # Will be injected via Jenkins credentials at runtime
