apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: vijay2359/cus-wordpress:${IMAGE_TAG}  # Dynamically replaced in Jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_PASSWORD
          value: "${DB_PASSWORD}"  # Injected via Jenkins credentials
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_HOST



          
