apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: vijay2359/cus-wordpress:${IMAGE_TAG}  
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_TABLE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_TABLE_PREFIX
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_CONFIG_EXTRA  
          value: |
            define('DB_NAME', getenv('WORDPRESS_DB_NAME'));
            define('DB_USER', getenv('WORDPRESS_DB_USER'));
            define('DB_PASSWORD', getenv('WORDPRESS_DB_PASSWORD'));
            define('DB_HOST', getenv('WORDPRESS_DB_HOST'));
            define('DB_CHARSET', 'utf8');
            define('DB_COLLATE', '');
            define('WP_DEBUG', false);
            $table_prefix = getenv('WORDPRESS_TABLE_PREFIX');
