apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: vijay2359/cus-wordpress:${IMAGE_TAG}  
        imagePullPolicy: Always
        ports:
        - containerPort: 80
       envFrom:
        - configMapRef:
            name: wordpress-config
        - secretRef:
            name: wordpress-secrets
            secretKeyRef:
              
        - name: WORDPRESS_CONFIG_EXTRA  
          value: |
            define('DB_NAME', getenv('WORDPRESS_DB_NAME'));
            define('DB_USER', getenv('WORDPRESS_DB_USER'));
            define('DB_PASSWORD', getenv('WORDPRESS_DB_PASSWORD'));
            define('DB_HOST', getenv('WORDPRESS_DB_HOST'));
            define('DB_CHARSET', 'utf8');
            define('DB_COLLATE', '');
            define('WP_DEBUG', false);
            $table_prefix = getenv('WORDPRESS_TABLE_PREFIX');
