apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{NAMESPACE}}  # Will be replaced dynamically for QA
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: wordpress-config
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "${DB_PASSWORD}"  # Will be injected via Jenkins credentials
